name: Tests-mac

on:
   workflow_dispatch:
     inputs:
       ref:
         required: true
         type: string
         default: 'develop'

jobs:
  test-call-develop:
     if: ${{inputs.ref == 'develop'}}
     strategy:
       fail-fast: false
       matrix:
         os: [macos-latest]
         py: [3.7, 3.8, 3.9, "3.10"]
         exclude:
           - os: macos-latest
             py: "3.7"
         include:
           - os: macos-13
             py: "3.7.17"
     uses: sammnnz/geompy/.github/workflows/tests.yml@develop
     with:
        os: ${{matrix.os}}
        py: ${{matrix.py}}
        ref: ${{inputs.ref}}
     secrets:
       token: ${{ secrets.GITHUB_TOKEN }}